version: '3'

services:
   auth_service:
    container_name: auth_service
    build:
      context: ./auth
      dockerfile: Dockerfile
    volumes:
      - ./auth/src/:/usr/src/app/src/
      - /usr/src/app/node_modules
    networks:
      - trantor_market_network
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
    depends_on:
      - auth_service_db
   auth_service_db:
    container_name: auth_service_db
    image: mongo
    volumes:
      - ./auth/db:/data/db
    restart: always
    ports:
      - 27017:27017
    networks:
      - trantor_market_network
networks:
  trantor_market_network:
    driver: bridge