version: '3'

services:
   auth_service:
    container_name: auth_service
    build:
      context: ./auth
      dockerfile: Dockerfile
    volumes:
      - ./auth/src/:/usr/src/app/src/
      - /usr/src/app/node_modules
    networks:
      - trantor_market_network
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
networks:
  trantor_market_network:
    driver: bridge